scikit-learn-contrib/category_encoders

- README.md
Thanks for all the help on getting the feedstock going!
This adds a minimal shout out to that work on the README!
> add conda option

- MANIFEST.in
This adds LICENSE.md to MANIFEST.in... it's nice to have this included along with the metadata for packaging!
> Add LICENSE.md to MANIFEST.in

- category_encoders/ordinal.py
- category_encoders/tests/test_encoders.py
> Fit with mapping

- category_encoders/ordinal.py
> fix deprecation warning with values

- category_encoders/leave_one_out.py
Sorry, when i fix the randomized style. I made a mistake in a if condition....
@wdm0006
> fix randomize bug for #29

- category_encoders/binary.py
This is an initial very barebones solution to #34
> In binary.py, moved the calculation of required number of digits to fit

- joss/paper.md
> adding to authors list (#47)

- joss/paper.md
> Added myself as contributor to paper.md  (#47)

- joss/paper.md
> add info into paper.md

- docs/source/index.rst
Add following classes to index.rst
- BaseN
- LeaveOneOut
- Target Encoding
> Update docs to reflect the latest changes

- category_encoders/ordinal.py
Issue: https://github.com/scikit-learn-contrib/categorical-encoding/issues/64
> ordinal encoder mapping argument docstring details

- category_encoders/binary.py
Fixes #80 
For a small test case, I ran the following:
```python
import category_encoders as ce
import numpy as np
import pandas as pd
df = pd.DataFrame({'a': np.random.randint(0,high=10, size=10000)})
be = ce.BinaryEncoder(cols=['a'])
```
And timed `be.fit_transform(df)`. On master, it ran in 101 ms, with this PR, it ran in 18ms.
> ENH: Performance improvement for BinaryEncoder

- category_encoders/basen.py
- category_encoders/tests/helpers.py
fixes column order for basen inverse transform
> Fix column order in basen inverse_transform

- category_encoders/basen.py
- category_encoders/tests/helpers.py
Reverts scikit-learn-contrib/categorical-encoding#172
> Revert "Fix column order in basen inverse_transform"

- category_encoders/hashing.py
1. Fix bug of multiprocessing. Now ``max_process`` works on Windows.
2. The parameter ``max_process`` is set to 1 as default for Windows, and automatically (commonly, CPU cores num) for others.
> Fix bug of multiprocessing on Windows

- .github/workflows/docs.yml
- .github/workflows/pypi-publish.yml
- .github/workflows/test-docs-build.yml
- .github/workflows/test-suite.yml
- category_encoders/count.py
- category_encoders/ordinal.py
- tests/test_count.py
- tests/test_ordinal.py
- Update github workflows to api version 2.x    
- Re-add python 3.5 support in github workflows  
- Add python 3.9 and 3.10 support in github workflows.  
- Fixes #330
> updated github workflows

- category_encoders/quantile_encoder.py
Update Summary Encoder docs #338
> update docs #338

- category_encoders/leave_one_out.py
- docs/requirements.txt
Fixes #353 
In LOO cast to original datatype of categorical data rather than always strings
> fixed bug in LOO encoder reported in #353

- category_encoders/target_encoder.py
- tests/test_target_encoder.py
- Add a test for trivial hierarchy
- Simplify code for target encoder
> add minor details after pull request 366

- category_encoders/hashing.py
Fixes #371 
- Use while loop instead of recursion in hashing encoder
- This avoids reaching the maximum recursion depth for small step sizes
> Fix recursion in hashing encoder

- CHANGELOG.md
- README.md
- category_encoders/__init__.py
- category_encoders/gray.py
- docs/source/gray.rst
- docs/source/index.rst
- tests/test_encoders.py
- tests/test_gray.py
- Adds gray encoder as suggested in #300
> added gray encoder

- category_encoders/target_encoder.py
Fixes #377 
Change from manual signoid calculation to more stable scipy implementation
> Numerical Stability fix for TargetEncoder

- category_encoders/one_hot.py
- category_encoders/wrapper.py
Fixes #
Changed from iteritems to item
Fixes #378
> Deprecation clean up

- category_encoders/cat_boost.py
> [DOC] Catboost docs reformulation

- category_encoders/backward_difference.py
- category_encoders/basen.py
- category_encoders/binary.py
- category_encoders/cat_boost.py
- category_encoders/count.py
- category_encoders/glmm.py
- category_encoders/gray.py
- category_encoders/hashing.py
- category_encoders/helmert.py
- category_encoders/james_stein.py
- category_encoders/leave_one_out.py
- category_encoders/m_estimate.py
- category_encoders/one_hot.py
- category_encoders/ordinal.py
- category_encoders/polynomial.py
- category_encoders/quantile_encoder.py
- category_encoders/sum_coding.py
- category_encoders/target_encoder.py
- category_encoders/utils.py
- category_encoders/woe.py
- category_encoders/wrapper.py
- tests/test_encoders.py
Fixes #348 
- introduce `get_feature_names_out` function in accordance to sklearn guidelines
- deprecate `get_feature_names`
> introduce get_features_name_out in accordance to sklearn guidelines

- category_encoders/wrapper.py
- tests/test_wrapper.py
Fixes #313 
- Initialize `feature_encoders` dict in each call to `fit`
- Simplify `fit_transform` of polynomial wrapper
> simplified polynomial wrapper, added tests, fixed bugs

- docs/source/index.rst
> Fix code blocks in index.rst

- category_encoders/base_contrast_encoder.py
- category_encoders/basen.py
- category_encoders/count.py
- category_encoders/one_hot.py
- category_encoders/ordinal.py
- examples/benchmarking_large/catboost_comparison.py
Fixes #422 
Remove all 7 uses of `inplace`.
> Remove uses of inplace

- CHANGELOG.md
- category_encoders/utils.py
- tests/test_encoders.py
> Fixes #453. Categorical targets.
