tests/test_encoders.py
Updated test dataset dataframe column name C to C1. This will address conflicts caused by patsy as 'C' is used to denote categorical variable by patsy
=> Fixed the test cases failing issue due to conflicts with patsy

tests/test_encoders.py
Apparently, windows `int` and `float` are not `==` to most dtypes, causing two test fails:
https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.4847/job/iqs0wu1u7jcamxs3#L418
This adds use of `numpy.issubdtype` for an (apparently) more robust comparison.
=> use numpy.issubdtype instead of equality for numericness

category_encoders/one_hot.py, category_encoders/tests/test_encoders.py
@wdm0006 PR to address https://github.com/scikit-learn-contrib/categorical-encoding/issues/19
Have `OneHotEncoder` expand all the classes/categories that were `fit`, instead of just the classes that were passed in to `transform`.
=> Enable a full class transform for OneHotEncoder

category_encoders/ordinal.py
it seems better to use the pandas ordering of `Uniques are returned in order of appearance` https://pandas.pydata.org/pandas-docs/stable/generated/pandas.unique.html#pandas.unique rather than something random. This way the models are reproducible
=> consistent ordering for categories

README.md, category_encoders/__init__.py, category_encoders/target_encoder.py, category_encoders/tests/test_encoders.py, docs/source/targetencoder.rst
As per #40 
Implements Target encoder. Code is based on the leave one out and implements approach described in 
* https://www.slideshare.net/0xdata/feature-engineering-83511751
* https://www.kaggle.com/ogrellier/python-target-encoding-for-categorical-features
* https://kaggle2.blob.core.windows.net/forum-message-attachments/225952/7441/high%20cardinality%20categoricals.pdf
=> Add Target Encoder #40

category_encoders/ordinal.py
I've added an optimization to `OrdinalEncoder.ordinal_encoding`. When the number of categories is large, `OrdinalEncoder` (and also other encoders using `OrdinalEncoder`) is very slow because of the for loops and `pandas.DataFrame.iloc`. So, for loops in `ordinal_encoding` are removed and replaced by using `pandas.Series.map`. 
All `nosetests --with-coverage` tests has been passed.
Any comment is warmly welcome. Here is my benchmarks.
```py
In [1]: import category_encoders as ce
In [2]: %%time
...: many_categories_list = ["category_{}".format(i) for i in range(10000)]
...: encoder = ce.OrdinalEncoder()
...: encoder.fit(many_categories_list)
...: encoder.transform(many_categories_list)
...:
CPU times: user 1min 8s, sys: 835 ms, total: 1min 9s
Wall time: 1min 11s
```
```python
In [1]: …
```
=> optimizing ordinal_encoding

category_encoders/one_hot.py, category_encoders/tests/test_encoders.py
@wdm0006 
addresses this issue: https://github.com/scikit-learn-contrib/categorical-encoding/issues/42
=> added option to include category values in encoded column names

category_encoders/ordinal.py
If `handle_unknown='impute'`, unknown categories will be encoded to 0 when `transform` is called. 
The docstring says unknown categories will be encoded to -1,  which is wrong.
=> Correct the docstring

category_encoders/backward_difference.py, category_encoders/helmert.py, category_encoders/polynomial.py, category_encoders/sum_coding.py
Columns named with awkward names including restricted characters such as "-" (dashes) will get evaluated to minus signs through patsy which requires their wrapping using the Q builtin.
http://patsy.readthedocs.io/en/latest/builtins-reference.html#patsy.builtins.Q
Minimum broken example:
```python
import pandas as pd
import category_encoders as ce
X = pd.DataFrame([1, 2, 3, 4], columns=['test-broken'])
X_trans = ce.HelmertEncoder(cols=['test-broken']).fit_transform(X)
```
Raises the error:
> patsy.PatsyError: Error evaluating factor: NameError: name 'col_test' is not defined
C(col_test-broken, Helmert)
=> Fix patsy naming issue

category_encoders/target_encoder.py, category_encoders/tests/test_encoders.py
Here is the PR to address https://github.com/scikit-learn-contrib/categorical-encoding/issues/109
The fix was to pass `smoothing` and `min_samples_leaf` into the `target_encode` function for the fit function. 
I had some trouble finding test methods that worked for python3 and 2. 
I also found an issue where the calculation in python 2 was incorrect because the `-(n-k)/f` division was integer division leaving off the decimal. So I cast the smoothing to a float which fixed the python 2 issue.
Also, we were recalculating the means in the map when we already did so at the pandas level, so I removed that too as it was also causing python 2 problems.
Let me know what you think.
=> Issue 109 smoothing min sample

category_encoders/leave_one_out.py, category_encoders/tests/test_encoders.py
Addresses https://github.com/scikit-learn-contrib/categorical-encoding/issues/106
To make the LeaveOneEncoder retrainable we follow @janmotl suggestion and split the `leave_one_out` method into methods for fit and transform respectively.
Even once that is done, the refit would fail because fit would set `self.cols` if `cols` is not passed into the constructor. To alleviate that problem, the `cols` from constructor get set to `self.static_cols` and in the fit method we set `self.cols` to `self.static_cols` if it is not none. If `self.static_cols` is None, then set `self.cols` to `get_obj_cols(X)`. So, we can retrain the encoder without specifying the columns in the constructor when each new DataFrame has different columns. That was my solution, please tell me what you think.
=> Issue 106 retrain leave one out

README.md, category_encoders/basen.py, category_encoders/binary.py, category_encoders/one_hot.py, category_encoders/ordinal.py, category_encoders/tests/test_encoders.py, category_encoders/tests/test_one_hot.py, category_encoders/tests/test_ordinal.py, category_encoders/tests/test_target_encoder.py, category_encoders/tests/test_utils.py, category_encoders/tests/test_woe.py, category_encoders/utils.py
Addresses https://github.com/scikit-learn-contrib/categorical-encoding/issues/86
@janmotl Here is my approach to setting up categorical datatype compatibility.
I've also started storing the datatype of the column so that way the inverse transform can set the types correctly. Luckily, there were not a lot of core things that had to change.
I was also able to ensure the ordinal encoder set it's values by the order of the categories in the data type.
Tell me what you think.
=> Categorical handling

category_encoders/leave_one_out.py, category_encoders/tests/test_leave_one_out.py
Over 400X faster while using less memory.
Store category mappings as DataFrames, then do vectorized apply
with `.map()`.  `fit()` just computes the sum and count of `y` for each
level of each column of `X`.  These mappings are stored as a dict
mapping the column name to a DataFrame with `sum` and `count` columns.
`transform()` then applies the map to each column of `X`, plus a little
vectorized math.
There is a speed/space tradeoff, whether to store the mean of `y`
for each level as well as the sum and count.  This was resolved
in favor of space, recomputing the mean in `transform()`, so that
e.g. pickled Transformers will take less space on disk.
```
rows, cats = 1000000, 1000
X = pd.DataFrame({'x': np.random.randint(0, cats, rows).astype(str)})
y = pd.Series(np.random.rand(rows))
%time …
```
=> Speed up LeaveOneOutEncoder with vectorization.

category_encoders/__init__.py, category_encoders/tests/helpers.py, category_encoders/tests/test_encoders.py, category_encoders/tests/test_helpers.py, category_encoders/tests/test_leave_one_out.py, category_encoders/tests/test_one_hot.py, category_encoders/tests/test_ordinal.py, category_encoders/tests/test_target_encoder.py, category_encoders/tests/test_woe.py
As discussed in [#169](https://github.com/scikit-learn-contrib/categorical-encoding/pull/169), renamed test_helper to helper and added unit tests for it.
=> Refactoring of test_helper

category_encoders/one_hot.py, category_encoders/tests/test_encoders.py, category_encoders/tests/test_polynomial.py, category_encoders/tests/test_woe.py
Both had an issue with the order of columns when doing inverse_transform.
This is fixed. Also, the new column na_categorical that is added in tests.helper is now present in test_encoders.test_classification(), making all tests pass.
=> Fix basen and onehot inverse transform colnames

category_encoders/ordinal.py, category_encoders/tests/test_ordinal.py
OrdinalEncoder and OneHotEncoder display incorrect results with categorical columns that include NaN values. 
```python
import numpy as np
import pandas as pd
from category_encoders import OrdinalEncoder, OneHotEncoder
X = pd.DataFrame({
'A': pd.Categorical(['a', 'b', 'c', 'a', np.nan]),
'B': ['a', 'b', 'c', 'a', np.nan]
})
OrdinalEncoder().fit_transform(X)
#>                      A  B
0                    1  1
1                    2  2
2                    3  3
3                    1  1
4 -9223372036854775808  4
OneHotEncoder(use_cat_names = True).fit_transform(X)
#>    A_a  A_b  A_c  B_a  B_b  B_c  B_nan
0  1.0  0.0  0.0    1    0    0      0
1  0.0  1.0  0.0    0    1    0      0
2  0.0  0.0  1.0    0    0    1      0
3  1.0  0.0  0.0    1    0    0      0
4  NaN  NaN  NaN    0    0 …
```
=> Fix OrdinalEncoder with categorical columns containing NaN values

category_encoders/ordinal.py, category_encoders/tests/test_ordinal.py
Closes #235.
When using the meta-data of the pandas categorical dtype to determine
all unique values, it might create an encoding for values not present in
the data. Ignoring the meta-data and using the seen unique values
instead ensures proper behavior when a new value occurs in the test
data. It will be handled through the handle_unknown strategy
accordingly.
---
This PR is opened prematurely, sorry for that. I still need to add test the fix and add a unit test.
Unfortunately I encountered issues running the unit tests locally.
I tried to, but got this error while running tests (on Py3.6.10, with pandas 1.0.1 and 0.25.3):
```
Traceback (most recent call last):
File "~\continuum\anaconda3\envs\ce\lib\multiprocessing\process.py", line 258, in _bootstrap
self.run()
File …
```
=> Determine unique values from data, not pandas.cat

category_encoders/cat_boost.py, category_encoders/james_stein.py, category_encoders/leave_one_out.py, category_encoders/m_estimate.py, category_encoders/mixed.py, category_encoders/target_encoder.py, category_encoders/utils.py, category_encoders/woe.py
Calling `fit_transform` for encoders that need target information an incorrect Error was raised:
```python
from category_encoders import *
import pandas as pd
from sklearn.datasets import load_boston
bunch = load_boston()
y = bunch.target
X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
enc = JamesSteinEncoder(cols=['CHAS', 'RAD'])
numeric_dataset = enc.fit_transform(X)
```
Leads to the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-32026f14b053> in <module>
6 X = pd.DataFrame(bunch.data, columns=bunch.feature_names)
7 enc = JamesSteinEncoder(cols=['CHAS', 'RAD'])
----> 8 numeric_dataset = enc.fit_transform(X) …
```
=> Fix Error Message in Fit_Transform

category_encoders/hashing.py, tests/test_hashing.py
Fix: #254 
- Disable ignore_index option
- From what I see, it doesn't seem necessary to specify ignore_index, so I suggest not to do so.
- add test code
=> Fix: #254 avoid resetting index in multi-process HashingEncoder

category_encoders/basen.py, tests/test_basen.py, tests/test_glmm.py
BaseNEncoder encoder used an incorrect formula for calculating the number of required bits in the output. If there are `nvals` distinct values and we reserve one encoding to represent "missing or unknown", then the correct number of bits is `ceil(log(nvals + 1, base))`. However, the code was previously using the formula `ceil(log(nvals, base)) + 1`.
Fixes https://github.com/scikit-learn-contrib/category_encoders/issues/264
- Change the formula to `ceil(log(nvals + 1, base))`.
- Switch the formula to use integer math so we don't have to worry about floating point rounding errors.
- Add a test.
- Fix a non-deterministic test.
=> Fix BaseNEncoder number of output columns

category_encoders/one_hot.py, tests/test_one_hot.py
Fixes #295
Prevents a column for missing values from being added in OneHotEncoder when handle_missing="error".  Does this by preventing the underlying OrdinalEncoder from producing the mapping NaN->-2, by setting _its_ handle_missing to "error" as well.
Also patches an incidental bug in OneHotEncoder.transform when handle_missing="error", when the input is not a frame.
Hacktoberfest?
=> Fix ohe nan col

category_encoders/backward_difference.py, category_encoders/basen.py, category_encoders/cat_boost.py, category_encoders/count.py, category_encoders/glmm.py, category_encoders/hashing.py, category_encoders/helmert.py, category_encoders/james_stein.py, category_encoders/leave_one_out.py, category_encoders/m_estimate.py, category_encoders/one_hot.py, category_encoders/ordinal.py, category_encoders/polynomial.py, category_encoders/quantile_encoder.py, category_encoders/sum_coding.py, category_encoders/target_encoder.py, category_encoders/woe.py
When I use `drop_invariant=True`, I get a `FutureWarning` because `df.drop` is switching to named kwargs only. This fixes it.
It should also be substantially more performant as the DF is only modified once.
=> Fix pandas future warning for dropping invariants

category_encoders/cat_boost.py
=> Small Typo in CatBoost Encoder

category_encoders/utils.py
After [scipy@1.8.0](https://github.com/scipy/scipy/blob/maintenance/1.8.x/scipy/sparse/csr.py), the `scipy.sparse.csr` namespace is deprecated. So `category_encoders` asserts the DeprecationWarning when it depends scipy:^1.8.0;
``` shell
$ python -Wd 
Python 3.10.4 (main, Apr  6 2022, 00:48:19) [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import category_encoders
(omitted)/python3.10/site-packages/category_encoders/utils.py:5: DeprecationWarning: Please use `csr_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.csr` namespace is deprecated.
from scipy.sparse.csr import csr_matrix
>>> category_encoders.__version__
'2.4.0'
>>> import scipy
>>> scipy.__version__
'1.8.0'
```
We need to use `csr_matrix` …
=> Avoid `DeprecationWarning` of scipy

category_encoders/leave_one_out.py
Replace `dict` constructor with `dict` comprehension In `category_encoders/leave_one_out.py`, because it is much faster.
=> Include dict comprehension

MANIFEST.in, setup.py
Fixes https://github.com/conda-forge/category_encoders-feedstock/pull/21
=> metadata tweaks for datasets in sdists

category_encoders/hashing.py
I used the hash-encoder the other day and was surprised by the time it takes for a theorically quite lightweight algorithm. 
I looked into it in a bit more detail, generating a random dataframe with 100,000 rows to measure performance. It turns out that in that case >50% of the time is spent in the `pandas.Series` constructor. [Here's my notebook](https://gist.github.com/bkhant1/b6780714831219a0b3d517849322b039) if you are curious!
- Returns the already-constructed list in `hash_fn` instead of `pandas.Series`, and use `result_type="expand"` in `apply` the expand the lists into a dataframe.
Here's the performance table comparision
| Dataframe #columns, #rows / #nb_components, #nb_process | `pandas.Series` | Raw `list` |
|----------|-------------|------|
| 3, 30 / 10, 4 | 5.05s | 5.23s |
| …
=> Improve hash-encoder performance - avoid unecessary Series construction

category_encoders/basen.py, tests/test_basen.py
Fixes https://github.com/scikit-learn-contrib/category_encoders/issues/392
Adds `re.escape()` when matching columns from the dataset, when doing `inverse_transform` in `BaseNEncoder`.
Without this `re.escape()`, any regex metacharacter is being interpreted by the regex engine, which leads to invalid results or exception being thrown.
=> Fix basen_to_integer when column name contains regex metachar

category_encoders/one_hot.py, tests/test_one_hot.py
Closes #386 
- added **ignore** option to the `handle_missing` parameter of the `OneHotEncoder`. This will encode `NaN` values as 0 in every dummy column. However, compared to the **value** option, no additional "_nan" category is created.
- added a simple test for the new option.
=> OneHotEncoder: Adding handle_missing='ignore' option

category_encoders/datasets/_base.py, requirements.txt, setup.py
Fixes increasingly loud warnings about the deprecation of `pkg_resources`, as seen on https://github.com/conda-forge/category_encoders-feedstock/pull/23
- replace use of `pkg_resources` with `importlib.metadata`
- or `importlib_metdata` on python < 3.9
- also removes an undeclared `setuptools` dependency, which is not _technically_ stdlib
=> replace pkg_resources with importlib.resources

category_encoders/utils.py
Fixes deprecation warning for pandas "is_categorical_dtype":
category_encoders/utils.py:50: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
Check:
https://github.com/pandas-dev/pandas/pull/33385
Replacing instances with the recommended alternative to use "isinstance"
=> Fix is_categorical_dtype deprecation

category_encoders/quantile_encoder.py, category_encoders/utils.py, tests/test_utils.py
Fixes #421
Adding dtypes `category`, `string` and `string[pyarrow]` to the default dtypes used to fit the encoders.
=> add category and string dtypes to default fit columns

CHANGELOG.md, category_encoders/hashing.py, tests/test_hashing.py
I used the HashingEncoder recently and found weird that any call to `fit` or `transform`, even for a dataframe with only 10s of rows and a couple of columns took at least 2s... 
I also had quite a large amount of data to encode, and that took a long time. 
That got me started on improving the performance of HashingEncoder, and here's the result! There are quite a few changes in there, each individual change should be in it's own commit, and here's a summary of the performance gain on my machine (macOS Monteray, i7 2.3ghz). 
|  | Baseline | Numpy arrays instead of apply | Shared memory instead of queue | Fork instead of spawn | Faster hashlib usage |
| --- | --- | --- | --- | --- | --- |
| n_rows=30 n_features=3 n_components=10 n_process=4 | 3.55 s ± 150 ms per loop (mean ± std. dev. of …
=> Optimise `HashingEncoder` for both large and small dataframes

category_encoders/cat_boost.py, category_encoders/utils.py, category_encoders/woe.py
Fixes #
We're converting the y to float in _transform function but not in fit function. And for other transforms as well, if we're required to do numerical calculation on y, we first convert it to float. This PR is to maintain the consitency in behaviour
-
-
-
=> if y is bool convert it into numerical

category_encoders/wrapper.py
Fixes #
Changed from y = pd.DataFrame(y, columns=['target']) to y = pd.DataFrame(y.rename('target')).
This is because if the original y is a pd.Series with a name other than 'target', pd.DataFrame(y, columns=['target']) returns an empty DataFrame.
The root cause of this problem is that in the function of utils.convert_input_vector(y, index) -> pd.Series, when a pd.Series or a single-column pd.DataFrame is passed as an argument, the process is designed to inherit the column name from the column name of the passed pd.Series or pd.DataFrame.
=> Fixed the DataFrame conversion of y in PolynomialWrapper's fit method

category_encoders/utils.py, requirements-dev.txt, tests/test_utils.py
Fixes #437
Resets `feature_names_out_` before applying `transform` (in case the latter uses the former, as when sklearn is set to pandas-output).
=> Fix for sklearn-pandas-out and refit

docs/source/index.rst
Fixed one word choice error in the sentence, "CategoryEncoders internally works with pandas DataFrames as apposed to sklearn, which works with numpy arrays." The phrase "as apposed to" should be "as opposed to."
=> Change apposed to opposed in index.rst
